apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels:
    kind: "mysql"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow

  ## --- Option 1: use nfs-server
  nfs:
    path: /mysql
    server: nfs01

  ## --- Option 2: use a path on nfs-server	
  #hostPath:
  #  path: /mysql

