apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  labels:
    kind: wordpress
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /html

#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  nfs:
#    path: /html
#    server: 127.0.0.1


