apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
  labels:
    kind: wordpress
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow

  ## --- Option 1: use nfs-server	
  nfs:
    path: /html
    server: nfs01

  ## --- Option 2 : use a path on a node
  #hostPath:
  #  path: /html
