apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
  selector:
    matchLabels:
      kind: "wordpress"
